### ISSUE TITLE
Serving Dynamic HTML how to add JS and CSS files

### ISSUE THREAD

**Issue by dohomi** [serverless/examples#32]
Hello,

I followed your examples on how to set the response to HTML. Now I am wondering how would I add CSS and JS to the HTML output? I was spinning my head around and tried some S3 alternatives but they are all not working on serverless 1.x

Thanks

**Comment by nikgraf** [comment]
@dohomi just static CSS & JS I would host via cloudfront or use tools like netlify or surge.sh. Have you seen this example? https://github.com/serverless/examples/tree/master/aws-node-single-page-app-via-cloudfront

**Comment by dohomi** [comment]
Hi @nikgraf thanks I successfully got this working. One question is bothering me now: I use internal VueJs to render subroutes. As soon the user is routing to a subroute and reloads the page, for sure the connection to the endpoint is gone. Is it possible to configure serverless, that the endpoint is listening to all incoming request like:
```
functions:
  vueLanding:
    handler: handler.vueLanding
    events:
      - http:
          method: get
          path: landing-page/** // is this somehow possible?
```
Or where would I need to forward all requests to my endpoint? I would like to run my serveress endpoint as a webserver which serves the HTML of a small internal NodeJS framework based on Vue SSR. Thanks
