### ISSUE TITLE
How to reference variable from environment variable and fallback to default value as a ref one?

### ISSUE THREAD

**Issue by Ali-Dalal** [serverless/examples#506]
Provider: AWS
I have the following resource in serverless.yml
```yml
resources:
  Resources:
    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName:${self:provider.stage}_my_queue
```
What I need to do is to reference an environment variable from .env file and fallback to ref MyQueue if .env file is missing that key.

referencing a resource is like this
```yml
MY_QUEUE:  { Ref: MyQueue }
```
how we can do it like this
```yml
MY_QUEUE: ${env:MY_QUEUE, {Ref: MyQueue} } # this not valid one
```
