### ISSUE TITLE
Endpoint Configuration type EDGE is not supported in this region: cn-north-1

### ISSUE THREAD

**Issue by tteat** [serverless/examples#516]
![image](https://user-images.githubusercontent.com/28376200/85936143-3a885680-b92a-11ea-9318-fb335d9aa4ee.png)

**Comment by wchaws** [comment]
@tteat 

Origin answer: https://stackoverflow.com/questions/54486891/endpoint-configuration-type-edge-is-not-supported-in-this-region/57022864#57022864

When importing a Body using Swagger, CFN ignores the EndpointConfiguration field. To work around this, try adding the endpointConfigurationTypes to the Parameters as per the below example:

```
ApiGatewayApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Parameters:
        endpointConfigurationTypes: REGIONAL
        ignore: documentation
      BodyS3Location:
        Bucket: BATS::SAM::CodeS3Bucket
        Key:xxxxxx
      EndpointConfiguration:
        Types:
        - REGIONAL
```
