### ISSUE TITLE
how do i pass multiple values to an environment variable?

### ISSUE THREAD

**Issue by nkhine** [serverless/examples#60]
how do i pass multiple values to an environment variable, this for me does not work:

```
service: serverless-test

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs4.3
  timeout: 10
# you can define service wide environment variables here
  environment:
    database: mongo
    MONGO_URI: "mongodb://mongo-6:27000,mongo-7:27000,mongo-8:27000/db-dev?replicaSet=mongo"
```
