### ISSUE TITLE
[BUG] node Express.js API with DynamoDB starter project fails at first deploy

### ISSUE THREAD

**Issue by ortimanu** [serverless/examples#683]
Hello. 

I initialized a new Serverless project in my machine using the Serverless Dashboard and the "node Express.js API with DynamoDB" starter/sample project. It initialized correctly but failed at deployment.

The command I executed was given to me by the dashboard:
```
npm i -g serverless && serverless \
    --org=manuelortizbey \
    --app=aws-node-express-dynamodb-api-starter \
    --name=aws-node-express-dynamodb-api-starter \
    --template=aws-node-express-dynamodb-api
```

 And the deployment error was:
```
Error:
CREATE_FAILED: UsersTable (AWS::DynamoDB::Table)
1 validation error detected: Value '${self:custom.tableName}' at 'tableName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+ (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: F769K1L3LU7S3HBL853CH05J6RVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)
```

However, I ran the `sls deploy` command after the error and everything worked correctly. Upon further inspection, I realized that something is happening on first deploy that the custom variable specified in the `serverless.yml` file of the template project is not being processed adecuately and it is using the templated value. I am referring to the one here (`TableName: ${self:custom.tableName})`:

```
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
```

That referenced the custom value initialized here:
```
custom:
  tableName: 'users-table-${sls:stage}'
```
Ergo, the error that CloudFormation returns.

This is not show stopping since it runs well after second execution, but it is worth a check to see why first deployment is failing. I will check further and update if I find anything else.
