### ISSUE TITLE
Do i have to comment these three lines before i deploy to aws?

### ISSUE THREAD

**Issue by hugetiny** [serverless/examples#714]
example: serverless-rest-api-with-dynamodb

```  
custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    # Comment if you don't have a DynamoDB running locally
      noStart: true
    migration:
      dir: offline/migrations
```
